[build]
  # Vite builds to 'dist' by default
  publish = "dist"
  # Vite build command
  command = "npm run build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

[[redirects]]
  # Redirección a Vercel - esta debe ir ANTES del fallback de SPA
  from = "/*"
  to = "https://rifa-papeleria.vercel.app/:splat"
  status = 301
  force = true

[[redirects]]
  # SPA fallback - serve index.html for all routes (fallback si la redirección anterior no funciona)
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Local development settings
  command = "npm run dev"
  port = 5173
  publish = "dist"