[build]
  command = "npm run build"
  publish = "build/client"

# Headers para optimización de rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets por 1 año
    Cache-Control = "public, max-age=31536000, immutable"
    # Preload critical resources
    Link = """</assets/firebase-*.js>; rel=preload; as=script,
              </assets/entry.client-*.js>; rel=preload; as=script,
              </assets/entry-*.css>; rel=preload; as=style"""

# Cache específico para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects con SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200